import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/components/Provider/ReduxProvider";
import QueryProvider from "@/components/Provider/TanstackProvider";

const inter = Inter({ subsets: ["latin"] });

// Color palatte : #121212, #1A1A1A, #512B81, #4477CE

export const metadata: Metadata = {
  title: "Financial Helper",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#121212]`}>
        <QueryProvider>
          <ReduxProvider>{children}</ReduxProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
